version: '2'
services:
    booktrade-app:
        image: booktrade
        external_links:
            - booktrade-postgresql:postgresql
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/booktrade
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    booktrade-postgresql:
        extends:
            file: postgresql.yml
            service: booktrade-postgresql
